;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; If we list all the natural numbers below 10 that are multiples of 3 or
;; 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

;; Find the sum of all the multiples of 3 or 5 below 1000.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defun sum35 (x)
  ;; not inclusive of x, it goes to x-1
  (setf a 0)
  (do
   ((i 1 (+ i 1)))
   ((> i (- x 1)) (return a))

    (when
     (or (= (mod i 3) 0) (= (mod i 5) 0))
      (setf a (+ a i)))
  ))

(sum35 1000)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Each new term in the Fibonacci sequence is generated by adding the
;; previous two terms. By starting with 1 and 2, the first 10 terms will
;; be:

;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; By considering the terms in the Fibonacci sequence whose values do notk
;; exceed four million, find the sum of the even-valued terms.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


(defun fib (x)
  ;; this is somewhat a for loop
  (let ((a 0)(b 1)(c 0)(s 0))
    (loop 
       (when (evenp a) (setf s (+ s a)))
       ;;(format t "a is ~s, s is ~s~%"  a s)
       (when (> (+ a b) x)(return s))
	(setf c a
	      a (+ a b)
	      b c)
       )))
(fib 4000000)


;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; The prime factors of 13195 are 5, 7, 13 and 29.

;; What is the largest prime factor of the number 600851475143 ?
;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun findPrime (x)
  ;; this is a while loop
  (loop while (= (mod x 2) 0)
     do (setf x (/ x 2))
       (print 2))

  ;(format t "current x is ~s~%" x)
  ;; this is a for loop
  (loop for i from 3 to (sqrt x) by 1
     do
       (loop while (= (mod x i) 0)
  	  do (setf x (/ x i))
  	    (print i))
       )

  (when (> x 2)
    (print x))
  )

(findPrime 13195)
(findPrime 600851475143)





;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; A palindromic number reads the same both ways. The largest
;; palindrome made from the product of two 2-digit numbers is 9009 =
;; 91 × 99.

;; Find the largest palindrome made from the product of two 3-digit
;; numbers.
;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun rn (x)
  ;; reverse a number in order
  (setf s 0)
  (loop while (> x 0)
     do
       (setf rr (rem x 10)
	     a (floor (/ x 10))
	     x a
	     s (+ rr (* 10 s)))
	)
  s
)

(defun parProd ()
  (setf ret 0)
  (loop for i from 101 to 1000 do
       (loop for j from 101 to 1000 do
	  (when (and (= (* i j) (rn (* i j))) (> (* i j) ret))
	    (setf ret (* i j)))
	  )
       )
  ret
  ;; last value will be returned by default
  )

;; not (parProd ())
(parProd)




;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 2520 is the smallest number that can be divided by each of the
;; numbers from 1 to 10 without any remainder.

;; What is the smallest positive number that is evenly divisible by
;; all of the numbers from 1 to 20?
;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defun eval5 (x)
  (setq f (list 11 12 13 14 15 16 17 18 19 20))
  ;;(setq f (list 1 2 3 4 5 6 7 8 9 10))
  (loop for i in f
     do
       (setf r (rem x i))
       (when (/= r 0) (return r))
       )
  )

(eval5 5040)

(let ((a (* 2520 19 17 13 11)))
  (loop
     (setq a (+ a 2520))
     (unless (eval5 a) (return a))
       ))

;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; The sum of the squares of the first ten natural numbers is,

;; 12+22+...+102=385 The square of the sum of the first ten natural
;; numbers is,

;; (1+2+...+10)2=552=3025 Hence the difference between the sum of the
;; squares of the first ten natural numbers and the square of the sum is
;; 3025−385=2640.

;; Find the difference between the sum of the squares of the first one
;; hundred natural numbers and the square of the sum.
;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(let ((s1 0)(s2 0))
  (loop for i from 1 to 100
     do
       (setf s1 (+ s1 i)
	     s2 (+ s2 (* i i))))
  (format t "s1 - s2 = ~s~%" (- (* s1 s1) s2))
  )



;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can
;; see that the 6th prime is 13.

;; What is the 10 001st prime number?
;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun findPrime1 (x)
  ;; this is a while loop
  (setq a (list 0))

  (loop while (= (mod x 2) 0)
     do (setf x (/ x 2))
       (push 2 (cdr (last a)))
       )

  ;(format t "current x is ~s~%" x)
  ;; this is a for loop
  (loop for i from 3 to (sqrt x) by 1
     do
       (loop while (= (mod x i) 0)
  	  do (setf x (/ x i))
	    (push i (cdr (last a)))
	    )
       )
  (when (> x 2)
    (push x (cdr (last a)))
    )
  a
  )

(let ((i 1) (n 0) (s 10001))
  (loop while (< n s)
     do
       (setf i (+ i 1))
       (when (= (length (findprime1 i)) 2)
	 (setq n (+ n 1)))

       (when (= n s) (print i))
       ))



;; The four adjacent digits in the 1000-digit number that have the
;; greatest product are 9 × 9 × 8 × 9 = 5832.

;; 73167176531330624919225119674426574742355349194934
;; 96983520312774506326239578318016984801869478851843
;; 85861560789112949495459501737958331952853208805511
;; 12540698747158523863050715693290963295227443043557
;; 66896648950445244523161731856403098711121722383113
;; 62229893423380308135336276614282806444486645238749
;; 30358907296290491560440772390713810515859307960866
;; 70172427121883998797908792274921901699720888093776
;; 65727333001053367881220235421809751254540594752243
;; 52584907711670556013604839586446706324415722155397
;; 53697817977846174064955149290862569321978468622482
;; 83972241375657056057490261407972968652414535100474
;; 82166370484403199890008895243450658541227588666881
;; 16427171479924442928230863465674813919123162824586
;; 17866458359124566529476545682848912883142607690042
;; 24219022671055626321111109370544217506941658960408
;; 07198403850962455444362981230987879927244284909188
;; 84580156166097919133875499200524063689912560717606
;; 05886116467109405077541002256983155200055935729725
;; 71636269561882670428252483600823257530420752963450

;; Find the thirteen adjacent digits in the 1000-digit number that have
;; the greatest product. What is the value of this product?

(defvar *in*
  (remove #\newline 
"73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450
"))

*in*

(let ((a *in*)
      (p 1)
      (n 13)
      (ret 0))
  (loop for i from 0 to (- (length a) n)
     do
       (loop for j from 0 to (- n 1)
	  do
	    (setq p (* p (digit-char-p (aref a (+ i j)))))
	    )
       (when (> p ret) (setq ret p))
       (setq p 1)
       )
  ret
  )



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

;; a^2 + b^2 = c^2
;; For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

;; There exists exactly one Pythagorean triplet for which a + b + c = 1000.
;; Find the product abc.
;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(loop for a from 1 to 1000
   do
     (loop for b from 1 to 1000
	do
	  (when (and (= (+ (* a a) (* b b)) (* (- 1000 a b) (- 1000 a b))) (< a b))
	    (print (list a b (- 1000 a b)))
	    (print (* a b (- 1000 a b)))
	    )))



;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

;; Find the sum of all the primes below two million.
;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


(let ((s 0)
      ;;(upbound 10))
      (upbound 2000000))
  (loop for x from 2 to upbound do 
       (if (or
	    (/= (rem x 2) 0)
	    (/= (rem x 3) 0)
	    (/= (rem x 5) 0)
	    (/= (rem x 7) 0)
	    (/= (rem x 11) 0)
	    (/= (rem x 13) 0)
	    )
	   (when (= (length (findprime1 x)) 2)
	     (setf s (+ s x))
	     )))
  s
  )


(defun isPrime (x)
  (if (<= x 1) (return-from isPrime nil))
  (loop for i from 2 to (sqrt x) do
       (if (= (rem x i) 0)(return-from isPrime nil)))
  t
  )

(isPrime 892384)
(isPrime 2038074743)
(isPrime 22801763489)

(let ((s 0)
      (n 2000000))
      ;;(n 10))
  (loop for i from 1 to n do
     (if (isPrime i) (setq s (+ s i))))
  s
  )




;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; In the 20×20 grid below, four numbers along a diagonal line have
;; been marked in red.

;; 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
;; 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
;; 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
;; 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
;; 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
;; 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
;; 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
;; 67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
;; 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
;; 21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
;; 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
;; 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
;; 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
;; 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
;; 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
;; 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
;; 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
;; 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
;; 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
;; 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

;; The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

;; What is the greatest product of four adjacent numbers in the same
;; direction (up, down, left, right, or diagonally) in the 20×20 grid?
;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ql:quickload :cl-ppcre)

(setq strs "1 3 2
1 3 3
1 2 3")

(setq b (substitute #\space #\newline strs))
(setq l (cl-ppcre:split "\\s+" b))

(setq ret (make-array '(3 3)))

(let ((c 0)
      (r 0))
  (loop for x in l do
       (if (= c 3) (setq c 0
			 r (+ r 1)))
       (setf (aref ret r c) x)

       (format t "c: ~s, r: ~s, x :~s~%" c r x)
       (setq c (+ c 1))
  ))
l
ret
